import { JersyIcon, MaskIcon as MaskIcon } from "../../assets/Icons";
import { GiftLogo as GiftLogo } from "../../assets/Icons";
import { TicketLogo as TicketLogo } from "../../assets/Icons";
import { StarIcon as StarIcon } from "../../assets/Icons";
import React from "react";
const data = [
  {
    index: 1,
    indexName: "GAME STREAK",
    header: "1 game win streak prize",
    iconType: <StarIcon />,
    body: "NFL All Day Reward",
  },
  {
    index: 2,
    indexName: "GAME STREAK",
    header: "2 game win streak prize",
    iconType: <StarIcon />,
    body: "Rare NFL All Day Reward",
  },
  {
    index: 3,
    indexName: "GAME STREAK",
    header: "3 game win streak prize",
    iconType: <StarIcon />,
    body: "Rare NFL All Day",
  },
  {
    index: 4,
    indexName: "GAME STREAK",
    header: "4 game win streak prize",
    iconType: <GiftLogo />,
    body: "ShopBeerGear Gift Card",
  },
  {
    index: 5,
    indexName: "GAME STREAK",
    header: "5 game win streak prize",
    iconType: <GiftLogo />,
    body: "Gift Card + Rare NFL All Day ",
  },
  {
    index: 6,
    indexName: "GAME STREAK",
    header: "6 game win streak prize",
    iconType: <JersyIcon />,
    body: "NFL Jersey",
  },
  {
    index: 7,
    indexName: "GAME STREAK",
    header: "1 game win streak prize",
    iconType: <GiftLogo />,
    body: "NFL Jersey + Gift Card",
  },
  {
    index: 8,
    indexName: "GAME STREAK",
    header: "8 game win streak prize",
    iconType: <StarIcon />,
    body: "NFL Jersey + Gift Card",
  },
  {
    index: 9,
    indexName: "GAME STREAK",
    header: "8 game win streak prize",
    iconType: <TicketLogo />,
    body: "Season Tickets (2) + NFL Jersey",
  },
  {
    index: 10,
    indexName: "GAME STREAK",
    header: "10 game win streak prize",
    iconType: <StarIcon />,
    body: "Legendary NFL All Day",
  },
  {
    index: 11,
    indexName: "GAME STREAK",
    header: "11 game win streak prize",
    iconType: <TicketLogo />,
    body: "Legendary NFL All Day",
  },
  {
    index: 12,
    indexName: "GAME STREAK",
    header: "12 game win streak prize",
    iconType: <MaskIcon />,
    body: "Year’s Worth of Beer",
  },
  {
    index: 13,
    indexName: "GAME STREAK",
    header: "13 game win streak prize",
    iconType: <TicketLogo />,
    body: "Year of Beer + Season Tickets",
  },
  {
    index: 14,
    indexName: "GAME STREAK",
    header: "14 game win streak prize",
    iconType: <TicketLogo />,
    body: "Playoff Tickets (2)",
  },
];
export default data;

export const tickets = [
  {
    index: 1,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <StarIcon />,
    body: "NFL All Day Reward",
  },
  {
    index: 2,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <StarIcon />,
    body: "Rare NFL All Day Reward",
  },
  {
    index: 3,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <StarIcon />,
    body: "Rare NFL All Day Reward",
  },
  {
    index: 4,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <GiftLogo />,
    body: "ShopBeerGear Gift Card",
  },
  {
    index: 5,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <GiftLogo />,
    body: "ShopBeerGear Gift Card + NFL All Day Reward",
  },
  {
    index: 6,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <JersyIcon />,
    body: "NFL Jersey",
  },
  {
    index: 7,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <GiftLogo />,
    body: "NFL Jersey + ShopBeerGear Gift Card",
  },
  {
    index: 8,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <StarIcon />,
    body: "Two NFL game tickets",
  },
  {
    index: 9,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <TicketLogo />,
    body: "Two NFL game tickets + NFL Jersey",
  },
  {
    index: 10,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <StarIcon />,
    body: "NFL All Day Reward",
  },
  {
    index: 11,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <TicketLogo />,
    body: "NFL All Day Reward + Two NFL game tickets",
  },
  {
    index: 12,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <MaskIcon />,
    body: "Year’s Worth of Beer",
  },
  {
    index: 13,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <TicketLogo />,
    body: "Year’s Worth of Beer + Two NFL game tickets",
  },
  {
    index: 14,
    indexName: "GAME STREAK",
    header: "game win streak prize",
    iconType: <TicketLogo />,
    body: "Two NFL Playoff Tickets",
  },
];
